# Generated by Django 4.2.13 on 2024-10-11 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=100)),
                ('cmp_ceo', models.CharField(max_length=100)),
                ('cmp_image', models.FileField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(choices=[('Gurgaon', 'Gurgaon'), ('Bengaluru', 'Bengaluru'), ('England', 'England'), ('Dublin', 'Dublin')], max_length=100)),
                ('state', models.CharField(choices=[('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Maharashtra', 'Maharashtra'), ('New York City', 'New York City'), ('Chicago', 'Chicago'), ('San Francisco', 'San Francisco'), ('Toronto', 'Toronto'), ('Burlington', 'Burlington'), ('London', 'London')], max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada')], max_length=100)),
                ('primary_industry', models.CharField(choices=[('IT', 'IT'), ('Banking & Lending', 'Banking & Lending'), ('Accounting & Taxation', 'Accounting & Taxation'), ('Education', 'Education'), ('Grocery Stores', 'Grocery Stores'), ('Internet & Web Services', 'Internet & Web Services')], max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=255)),
                ('cmp_size', models.CharField(choices=[('more than 10,000', 'more than 10,000'), ('1,001 to 5,000', '1,001 to 5,000'), ('1,001 to 5,000', '1,001 to 5,000'), ('70-200', '70-200')], max_length=20)),
                ('founded_in', models.PositiveIntegerField()),
                ('facebook', models.URLField()),
                ('linked_in', models.URLField()),
                ('twitter', models.URLField()),
                ('website', models.URLField()),
                ('about_company', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
