# Generated by Django 4.2.13 on 2024-10-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_city_alter_company_primary_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cmp_size',
            field=models.CharField(choices=[('more than 10,000', 'more than 10,000'), ('1,001 to 5,000', '1,001 to 5,000'), ('500 to 1,000', '500 to 1,000'), ('70-200', '70-200'), ('50-100', '50-100'), ('10-25', '10-25')], max_length=20),
        ),
    ]
