# Generated by Django 4.2.13 on 2024-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_cmp_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='primary_industry',
            field=models.CharField(choices=[('IT', 'IT'), ('Manufacturing', 'Manufacturing'), ('Financial Services', 'Financial Services'), ('Accounting & Taxation', 'Accounting & Taxation'), ('Education', 'Education'), ('Grocery Stores', 'Grocery Stores'), ('Internet & Web Services', 'Internet & Web Services')], max_length=100),
        ),
    ]
