# Generated by Django 4.2.13 on 2024-10-11 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Maharashtra', 'Maharashtra'), ('New York City', 'New York City'), ('Chicago', 'Chicago'), ('San Francisco', 'San Francisco'), ('Toronto', 'Toronto'), ('Burlington', 'Burlington'), ('London', 'London')], max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada')], max_length=100)),
                ('experience', models.CharField(choices=[('0 - 2', '0 - 2'), ('3 - 10', '3 - 10'), ('11 - 40', '11 - 40')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], default='English', max_length=100)),
                ('education_level', models.CharField(choices=[('None', 'None'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=100)),
                ('linked_in', models.URLField()),
                ('twitter', models.URLField()),
                ('about_candidate', models.TextField()),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Trainee', 'Trainee')], max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(choices=[('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Maharashtra', 'Maharashtra'), ('New York City', 'New York City'), ('Chicago', 'Chicago'), ('San Francisco', 'San Francisco'), ('Toronto', 'Toronto'), ('Burlington', 'Burlington'), ('London', 'London')], max_length=100, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada')], max_length=100, null=True)),
                ('location_type', models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=255, null=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1500)),
                ('still_working_here', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255, null=True)),
                ('start_date', models.PositiveIntegerField()),
                ('end_date', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('still_schooling_here', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
