# Generated by Django 4.2.13 on 2024-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='candidate_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
