# Generated by Django 4.2.13 on 2024-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education_level',
            field=models.CharField(choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD'), ('Doctorate', 'Doctorate')], max_length=100),
        ),
    ]
