# Generated by Django 4.2.13 on 2024-10-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_qualification',
            field=models.CharField(choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_vacancy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
