# Generated by Django 4.2.13 on 2024-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_city_job_country_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
